FROM apache/airflow:3.3.1

USER airflow

RUN pip install --no-cache-dir \
    databricks-sdk \
    apache-airflow-providers-databricks \
    faker \
    pandas \
    pyarrow \
    boto3 \
    python-dotenv